export const Lavori : {id: number, titolo: string, img: string, urlLive: string, tec: string, urlRepo: string, descrizione: string }[] = [
    {id : 0, titolo: 'Mineverse', img: "media/frontPages/mineverse.png", urlLive: 'https://mineverse.netlify.app/', tec: 'media/react.svg', urlRepo: '', descrizione: "MineVerse offre un'esperienza immersiva per gli appassionati di Minecraft, combinando modalità innovative come Space Prison e SpaceVerse. Con un design accattivante e funzionalità intuitive, il sito permette agli utenti di esplorare regolamenti, tutorial e dettagli sulle modalità di gioco, semplificando l'accesso alle informazioni e arricchendo l’esperienza di gioco."},
    {id : 1, titolo: 'StarFishMc', img: "media/frontPages/starfish.png", urlLive: 'https://starfishmc.netlify.app/', tec: 'media/react.svg', urlRepo: '', descrizione: "StarfishMC è un sito web realizzato con React, progettato per rappresentare il server Minecraft in modo innovativo e coinvolgente. Grazie a un design accattivante e animazioni dinamiche, il sito offre informazioni dettagliate sulle modalità di gioco, come il Vanilla e WaterWorld, arricchendo l’esperienza degli utenti e invitandoli a esplorare il server in modo intuitivo."},
    {id : 2, titolo: 'Box-PVP', img: "media/frontPages/boxpvp.png", urlLive: 'https://box-pvp.netlify.app/#home', tec: 'media/ts.svg', urlRepo: '', descrizione: "Il sito Box-PvP è stato sviluppato per rappresentare il server Minecraft omonimo, che si concentra esclusivamente sulla modalità di gioco box-pvp. L'obiettivo principale del progetto era creare una piattaforma informativa e accattivante che rispecchiasse l'identità del server."},
    {id : 3, titolo: 'Shopping Cart', img: "media/frontPages/homepage.JPG", urlLive: 'https://shopping-cart-fashion.netlify.app/', tec: 'media/react.svg', urlRepo: 'https://github.com/ReXerses/Shopping-Cart', descrizione: "Shopping Cart offre un'esperienza user-friendly per gli utenti che  desiderano navigare tra i prodotti disponibili, aggiungere articoli al  carrello e gestire gli acquisti in modo efficiente. Con una serie di  funzionalità chiave e un design intuitivo, l'app si propone di  semplificare il processo di shopping online, offrendo agli utenti  un'esperienza fluida e piacevole."},
    {id : 4, titolo: 'CV Generator', img: 'media/frontPages/CV-gen.JPG', urlLive: 'https://curriculum-vitae-top.netlify.app/', tec: 'media/react.svg', urlRepo: 'https://github.com/ReXerses/CV-Application', descrizione: "CV Generator è un'applicazione web per la creazione di curriculum vitae in modo intuitivo e personalizzato. Offrendo un'esperienza utente fluida, l'app consente agli utenti di inserire informazioni personali, educative e lavorative, generando un CV professionale e accattivante."},
    {id : 5, titolo: 'Weather-App', img: 'media/frontPages/meteo-app.JPG', urlLive: 'https://rexerses.github.io/weather-app/', tec: 'media/js.svg', urlRepo: 'https://github.com/ReXerses/weather-app', descrizione: "Questo progetto rappresenta una Meteo App che offre un'esperienza intuitiva per ottenere le previsioni del tempo di una determinata città. La Meteo App si collega all'API di WeatherAPI per recuperare dati accurati e aggiornati sulle condizioni meteorologiche. L'interfaccia utente ben strutturata consente agli utenti di cercare rapidamente le previsioni per la propria città e di visualizzare dettagli come la temperatura attuale, la massima e la minima giornaliera, nonché le previsioni orarie."},
    {id : 6, titolo: 'Memory Card', img: 'media/frontPages/memory-card-game.JPG', urlLive: 'https://lovecraft-memory-card-game.netlify.app/', tec: 'media/react.svg', urlRepo: 'https://github.com/ReXerses/Memory-Card', descrizione: "Memory Card Game è un'applicazione web che offre un'esperienza divertente per gli appassionati di giochi di memoria. L'obiettivo del gioco è cliccare tutte le carte, evitando di cliccare due volte sulla stessa. La sfida consiste nel ricordare i nomi o le immagini delle carte e completare il gioco con il punteggio massimo."},
    {id : 7, titolo: 'BattleShip', img: 'media/frontPages/battleship.JPG', urlLive: 'https://rexerses.github.io/BattleShip/', tec: 'media/js.svg', urlRepo: 'https://github.com/ReXerses/BattleShip', descrizione: "Il progetto BattleShip è un'implementazione del classico gioco da tavolo 'Battaglia Navale' in formato web, offrendo un'esperienza coinvolgente e avvincente per gli appassionati di giochi strategici. Il gioco consente ai giocatori di collocare strategicamente le proprie navi sulla griglia e cercare di affondare la flotta avversaria. L'interfaccia utente chiara e ben strutturata facilita la navigazione e la comprensione delle dinamiche di gioco."},
];